version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  spark:
    image: apache/spark:3.5.0
    container_name: spark
    depends_on:
      - kafka
      - mongodb
    volumes:
      - ./spark:/app
      - ./ivy:/tmp/.ivy2
    environment:
      - HOME=/tmp
    command: >
      bash -c "
      pip install pymongo &&
      /opt/spark/bin/spark-submit
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0
      --conf spark.driver.extraJavaOptions=-Divy.home=/tmp/.ivy2
      --conf spark.executor.extraJavaOptions=-Divy.home=/tmp/.ivy2
      /app/streaming.py
      "

  mongodb:
    image: mongo:6
    ports:
      - "27018:27017"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - kafka
      - mongodb

  ml-service:
    build: ./ml-service
    depends_on:
      - kafka
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
